# Split windows using | and -
unbind '"'
unbind %
bind | split-window -h
bind - split-window -v
bind _ split-window -v

# change kill command to k
unbind &
bind k kill-pane

# passthru <C-up/down>
bind -n C-Up send-keys C-Up
bind -n C-Down send-keys C-Down

# Enable mouse mode
set -g mouse on

set-option -g repeat-time 250
